refactor(model): add v2 model
algoan/rest-nodejs pull request #45
Opened 2021-09-10 15:41 UTC by mbeuil

tp-64-34 time-5

add the following models : 
- Customer
- Analysis
- CreditInsights
- Score
- Account
- Transaction

## Description
Some Properties have their name with a V2, those are type that are already exported by the v1 models. I choose the V2 patern instead of something else. 
example: AccountType became AccountTypeV2.

I've separated 2 interfaces from the rest: Calendar and Aggregator cause the first is used by Analysis and CreditInsight, the second is shared by Account and Transaction.

I've based those model on what you can find in the analysis-manager. **I strongly encourage you to check everything** as I might have misunderstood something.

## Motivation and Context
Until now there was only the v1 models

## Types of changes
Since This PR only add the interface for now I've marked it as a reactor. Was there something else to do ?

2021-09-23 08:14 UTC, meriamBenSassi requested changes
Thanks @mbeuil  :D 
LGTM besides the failing CI due to the coverage. You can remove those files from the coverage since wi don't use them anywhere for now

2021-09-23 17:06 UTC, meriamBenSassi approved these changes

2021-09-23 17:07 UTC, meriamBenSassi commented
I added @ccoeurderoy because my merge won't trigger the publish

2021-09-24 08:10 UTC, ccoeurderoy approved these changes

2021-09-24 08:10 UTC, merged